apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "true"

  name: bitnami-kafka-ebr-01
  namespace: default
spec:
  chart:
    name: kafka
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    version: 14.9.3
  
  releaseName: bitnami-kafka-ebr-01
  targetNamespace: default
  helmVersion: v3
  values:
    replicaCount: 1
    containerPorts:
      client: 9096
  
    service:
      ports:
        client: 9096

    image:
      repository: bitnami/kafka
      tag: 2.8.1-debian-11-r5
      debug: true

